version: "3"

services:
  app:
    build: .
    container_name: nest_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: abc123
      DB_DATABASE: postgres
    ports:
      - "3050:3000" 
    networks:
      - sts-proxy

  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: abc123
      POSTGRES_DB: postgres
    ports:
      - "54322:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - sts-proxy

  pgweb:
    image: sosedoff/pgweb:latest
    restart: always
    environment:
      DATABASE_URL: "postgres://postgres:abc123@postgres:5432/postgres?sslmode=disable"
    ports:
      - "8989:8081"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - sts-proxy

networks:
  sts-proxy:
    driver: bridge
